---
# See https://github.com/jvautier/project-cli
fullname: jvautier/project-cli
description: Manage github/gitlab projects properties
tags:
  - github
  - gitlab
  - api
  - cli
github:
  has_issues: true
  has_projects: false
  has_wiki: false
